import { ListChecks } from "lucide-react";

type NextAction = { action_id?: string; label?: string; transform_id?: string | null; why?: string; expected_outputs?: string[]; required_api_key?: string | null; noise_risk?: string; mode?: string };

export default function NextActionPanel({ actions }: { actions?: NextAction[] | null }) {
  const items = actions || [];
  return (
    <article className="investigator-card">
      <header><ListChecks size={15} /><strong>Next Best Actions</strong><span>{items.length}</span></header>
      <div className="investigator-list">
        {items.slice(0, 6).map((item) => (
          <div key={item.action_id || item.label}>
            <strong>{item.label || "Review evidence"}</strong>
            <span>{item.transform_id || "analyst action"}{item.required_api_key ? ` / key: ${item.required_api_key}` : ""}</span>
            <small>{item.why || "Action generated by deterministic planner."}</small>
          </div>
        ))}
        {!items.length && <p className="empty-copy">No recommended action yet. Select a case with graph state.</p>}
      </div>
    </article>
  );
}
