PLATFORM_SOURCES = [
    {"name": "GitHub", "category": "developer", "url": "https://github.com/{username}", "type": "developer_profile"},
    {"name": "GitLab", "category": "developer", "url": "https://gitlab.com/{username}", "type": "developer_profile"},
    {"name": "Codeberg", "category": "developer", "url": "https://codeberg.org/{username}", "type": "developer_profile"},
    {"name": "Bitbucket", "category": "developer", "url": "https://bitbucket.org/{username}", "type": "developer_profile"},
    {"name": "npm", "category": "developer", "url": "https://www.npmjs.com/~{username}", "type": "package_profile"},
    {"name": "PyPI", "category": "developer", "url": "https://pypi.org/user/{username}/", "type": "package_profile"},
    {"name": "Docker Hub", "category": "developer", "url": "https://hub.docker.com/u/{username}", "type": "developer_profile"},
    {"name": "Hugging Face", "category": "developer", "url": "https://huggingface.co/{username}", "type": "developer_profile"},
    {"name": "Kaggle", "category": "data", "url": "https://www.kaggle.com/{username}", "type": "data_profile"},
    {"name": "Reddit", "category": "social", "url": "https://www.reddit.com/user/{username}", "type": "social_profile"},
    {"name": "X", "category": "social", "url": "https://x.com/{username}", "type": "social_profile"},
    {"name": "Instagram", "category": "social", "url": "https://www.instagram.com/{username}/", "type": "social_profile"},
    {"name": "TikTok", "category": "social", "url": "https://www.tiktok.com/@{username}", "type": "social_profile"},
    {"name": "YouTube", "category": "creator", "url": "https://www.youtube.com/@{username}", "type": "creator_profile"},
    {"name": "Twitch", "category": "creator", "url": "https://www.twitch.tv/{username}", "type": "creator_profile"},
    {"name": "Medium", "category": "writing", "url": "https://medium.com/@{username}", "type": "creator_profile"},
    {"name": "Dev.to", "category": "writing", "url": "https://dev.to/{username}", "type": "developer_profile"},
    {"name": "Hashnode", "category": "writing", "url": "https://hashnode.com/@{username}", "type": "creator_profile"},
    {"name": "Substack", "category": "writing", "url": "https://{username}.substack.com", "type": "creator_profile"},
    {"name": "Mastodon Social", "category": "social", "url": "https://mastodon.social/@{username}", "type": "social_profile"},
    {"name": "Product Hunt", "category": "startup", "url": "https://www.producthunt.com/@{username}", "type": "social_profile"},
    {"name": "Keybase", "category": "identity", "url": "https://keybase.io/{username}", "type": "identity_profile"},
    {"name": "Gravatar", "category": "identity", "url": "https://gravatar.com/{username}", "type": "identity_profile"},
    {"name": "About.me", "category": "identity", "url": "https://about.me/{username}", "type": "identity_profile"},
    {"name": "Linktree", "category": "identity", "url": "https://linktr.ee/{username}", "type": "identity_profile"},
    {"name": "Bio.link", "category": "identity", "url": "https://bio.link/{username}", "type": "identity_profile"},
    {"name": "Carrd", "category": "identity", "url": "https://{username}.carrd.co", "type": "identity_profile"},
    {"name": "Behance", "category": "creative", "url": "https://www.behance.net/{username}", "type": "creative_profile"},
    {"name": "Dribbble", "category": "creative", "url": "https://dribbble.com/{username}", "type": "creative_profile"},
    {"name": "Figma Community", "category": "creative", "url": "https://www.figma.com/@{username}", "type": "creative_profile"},
    {"name": "Vimeo", "category": "creator", "url": "https://vimeo.com/{username}", "type": "creator_profile"},
    {"name": "SoundCloud", "category": "creator", "url": "https://soundcloud.com/{username}", "type": "creator_profile"},
    {"name": "Bandcamp", "category": "creator", "url": "https://bandcamp.com/{username}", "type": "creator_profile"},
    {"name": "Steam", "category": "gaming", "url": "https://steamcommunity.com/id/{username}", "type": "gaming_profile"},
    {"name": "Roblox", "category": "gaming", "url": "https://www.roblox.com/user.aspx?username={username}", "type": "gaming_profile"},
    {"name": "Chess.com", "category": "gaming", "url": "https://www.chess.com/member/{username}", "type": "gaming_profile"},
    {"name": "Lichess", "category": "gaming", "url": "https://lichess.org/@/{username}", "type": "gaming_profile"},
    {"name": "Strava", "category": "fitness", "url": "https://www.strava.com/athletes/{username}", "type": "fitness_profile"},
    {"name": "Letterboxd", "category": "media", "url": "https://letterboxd.com/{username}/", "type": "media_profile"},
    {"name": "Goodreads", "category": "media", "url": "https://www.goodreads.com/{username}", "type": "media_profile"},
    {"name": "Pinterest", "category": "social", "url": "https://www.pinterest.com/{username}/", "type": "social_profile"},
    {"name": "Tumblr", "category": "social", "url": "https://{username}.tumblr.com", "type": "social_profile"},
    {"name": "Flickr", "category": "creative", "url": "https://www.flickr.com/people/{username}/", "type": "creative_profile"},
    {"name": "500px", "category": "creative", "url": "https://500px.com/p/{username}", "type": "creative_profile"},
    {"name": "Unsplash", "category": "creative", "url": "https://unsplash.com/@{username}", "type": "creative_profile"},
    {"name": "Buy Me a Coffee", "category": "finance", "url": "https://www.buymeacoffee.com/{username}", "type": "payment_profile"},
    {"name": "Patreon", "category": "finance", "url": "https://www.patreon.com/{username}", "type": "payment_profile"},
    {"name": "Ko-fi", "category": "finance", "url": "https://ko-fi.com/{username}", "type": "payment_profile"},
    {"name": "Cash App", "category": "finance", "url": "https://cash.app/${username}", "type": "payment_profile"},
    {"name": "OpenStreetMap", "category": "community", "url": "https://www.openstreetmap.org/user/{username}", "type": "community_profile"},
]

NEGATIVE_MARKERS = [
    "not found",
    "page not found",
    "user not found",
    "profile not found",
    "doesn't exist",
    "does not exist",
    "couldn’t find",
    "couldn't find",
    "404",
]

TRACKER_HINTS = {
    "Google Analytics": ["googletagmanager.com", "google-analytics.com", "gtag("],
    "Meta Pixel": ["connect.facebook.net", "fbq("],
    "Hotjar": ["hotjar.com"],
    "Cloudflare": ["cloudflareinsights.com", "cdn-cgi"],
    "Plausible": ["plausible.io"],
    "Segment": ["segment.com/analytics.js", "cdn.segment.com"],
    "Sentry": ["sentry.io", "browser.sentry-cdn.com"],
}
