from __future__ import annotations

from backend.playbooks.types import PlaybookDefinition, PlaybookStep


PLAYBOOKS = [
    PlaybookDefinition("email_investigation", "Email Investigation", "Validate mailbox syntax, workspace/domain posture, username candidates, and report-safe evidence.", ["email"], [PlaybookStep("email_workspace", "Workspace posture", "Resolve MX/TXT/provider posture.", "email_to_workspace"), PlaybookStep("email_gravatar", "Gravatar evidence", "Check public Gravatar avatar/profile evidence.", "email_to_gravatar"), PlaybookStep("email_username_candidates", "Username candidates", "Derive low-confidence username candidates from the email local-part.", "email_to_username_candidates"), PlaybookStep("email_profile_pivot", "Promote then profile pivot", "Promote a candidate username, then run Username -> Profiles with analyst confirmation.", None, True)], ["email_to_workspace", "email_to_gravatar", "email_to_username_candidates"], ["username_to_profiles", "email_to_breach_connectors"], ["No source URL or evidence hash", "Only candidates remain"], ["generic login pages", "candidate URL only"], ["Executive Summary", "Mailbox Posture", "Evidence", "Confidence", "Next Steps"]),
    PlaybookDefinition("username_investigation", "Username Investigation", "Resolve public profiles, links, avatar reuse, and weak/candidate separation.", ["username"], [PlaybookStep("username_profiles", "Public profile sweep", "Resolve target-specific public profile pages.", "username_to_profiles"), PlaybookStep("profile_links", "Profile link expansion", "Extract public profile links and self-declared websites.", "profile_to_links", True)], ["username_to_profiles"], ["profile_to_links", "profile_to_avatar"], ["No verified profile evidence"], ["soft 404", "auth wall", "generic login"], ["Profile Coverage", "Correlation", "Candidate Leads"]),
    PlaybookDefinition("domain_impersonation", "Domain Impersonation", "Compare domain infrastructure, RDAP, CT, favicon, and web fingerprint evidence.", ["domain", "url"], [PlaybookStep("domain_dns", "DNS posture", "Collect A/AAAA/MX/NS/TXT/CAA records.", "domain_to_dns"), PlaybookStep("domain_rdap", "RDAP", "Collect public registration/allocation metadata.", "domain_to_rdap"), PlaybookStep("domain_ct", "Certificate Transparency", "Collect public certificate names.", "domain_to_ct_subdomains"), PlaybookStep("favicon", "Favicon hash", "Compare reusable web asset fingerprints.", "domain_to_favicon_hash")], ["domain_to_dns", "domain_to_rdap"], ["domain_to_ct_subdomains", "domain_to_web_fingerprint", "domain_to_favicon_hash"], ["Official comparison domain missing"], ["CDN-only IP", "registrar privacy-only"], ["Risk Score", "Infrastructure Map", "IOC Table", "Takedown Notes"]),
    PlaybookDefinition("phone_investigation", "Phone Investigation", "Validate numbering plan and public-source/manual evidence without contact-sync abuse.", ["phone"], [PlaybookStep("numbering", "Numbering plan", "Validate E.164, carrier/region metadata.", "phone_to_numbering_plan"), PlaybookStep("deeplinks", "Public deeplink metadata", "Collect only public metadata; never claim registration from landing pages.", "phone_to_public_deeplinks", True)], ["phone_to_numbering_plan"], ["phone_to_public_deeplinks"], ["Phone is not valid E.164"], ["messenger landing page"], ["Phone Metadata", "Manual Evidence", "Caveats"]),
    PlaybookDefinition("crypto_wallet_investigation", "Crypto Wallet Investigation", "Collect public explorer balance/transaction pivots through configured connectors.", ["crypto_wallet"], [PlaybookStep("balance", "Wallet balance", "Fetch public explorer balance if connector is configured.", "check_wallet_balance"), PlaybookStep("trace", "Transaction trace", "Expand public transaction links with analyst confirmation.", "trace_transactions", True)], ["check_wallet_balance"], ["trace_transactions"], ["No public explorer connector configured"], ["dust spam transactions"], ["Wallet Summary", "Transactions", "Counterparties"]),
    PlaybookDefinition("website_clone_detection", "Website Clone Detection", "Compare web fingerprints, favicons, links, DNS, and CT evidence.", ["domain", "url"], [PlaybookStep("fingerprint", "Web fingerprint", "Collect public headers/title/meta and favicon.", "domain_to_web_fingerprint"), PlaybookStep("assets", "Asset reuse", "Hash visible web assets where public.", "domain_to_assets", True)], ["domain_to_web_fingerprint"], ["domain_to_assets", "domain_to_favicon_hash"], ["No official/source comparison evidence"], ["generic template pages"], ["Clone Indicators", "Shared Assets", "Evidence"]),
    PlaybookDefinition("threat_actor_infrastructure_mapping", "Threat Infrastructure Mapping", "Map public domain/IP/ASN/certificate relationships without private collection.", ["domain", "ip", "url"], [PlaybookStep("infra_dns", "DNS/IP map", "Collect DNS and reverse DNS.", "domain_to_dns"), PlaybookStep("rdap_asn", "RDAP/ASN", "Collect public allocation metadata.", "ip_to_rdap_asn"), PlaybookStep("ct", "CT expansion", "Expand certificate names cautiously.", "domain_to_ct_subdomains", True)], ["domain_to_dns", "ip_to_rdap_asn"], ["domain_to_ct_subdomains", "ip_to_reverse_dns"], ["Only CDN/shared hosting remains"], ["CDN-only", "shared hosting"], ["Infrastructure Map", "Confidence", "Noise Removed"]),

    PlaybookDefinition("fake_website_takedown_packet", "Fake Website Takedown Packet", "Prepare evidence-backed takedown support for suspected impersonation or clone domains.", ["domain", "url"], [PlaybookStep("dns", "DNS posture", "Collect DNS evidence.", "domain_to_dns"), PlaybookStep("rdap", "RDAP registration", "Collect public RDAP evidence.", "domain_to_rdap"), PlaybookStep("web", "Web fingerprint", "Collect page metadata and external links.", "domain_to_web_fingerprint"), PlaybookStep("report", "Report readiness", "Validate evidence and prepare report-safe packet.", None, True)], ["domain_to_dns", "domain_to_rdap", "domain_to_web_fingerprint"], ["domain_to_ct_subdomains"], ["No source URL", "Official brand comparison missing"], ["shared hosting", "registrar privacy only"], ["Takedown Evidence", "Domain Ownership", "Web Fingerprint", "Recommended Actions"], expected_outputs=["evidence_table", "ioc_table", "takedown_packet"], risk_noise_notes=["Do not claim malicious intent without direct public evidence."]),
    PlaybookDefinition("infrastructure_mapping", "Infrastructure Mapping", "Map public DNS, RDAP, ASN, CT, and web fingerprints for infrastructure clusters.", ["domain", "ip", "url"], [PlaybookStep("dns", "DNS/IP expansion", "Collect DNS records.", "domain_to_dns"), PlaybookStep("rdap", "RDAP/ASN", "Collect allocation metadata.", "ip_to_rdap_asn"), PlaybookStep("ct", "CT expansion", "Expand public certificate names with analyst review.", "domain_to_ct_subdomains", True)], ["domain_to_dns", "ip_to_rdap_asn"], ["domain_to_ct_subdomains", "domain_to_web_fingerprint"], ["Only CDN/shared infrastructure remains"], ["CDN-only", "shared hosting"], ["Infrastructure Map", "Confidence", "Noise Removed"], expected_outputs=["same_infrastructure_hypotheses", "ioc_table"]),
    PlaybookDefinition("phone_public_metadata", "Phone Public Metadata", "Validate public numbering metadata without contact-sync, OTP, or registration probing.", ["phone"], [PlaybookStep("numbering", "Numbering plan", "Validate E.164 and public metadata.", "phone_to_numbering_plan")], ["phone_to_numbering_plan"], [], ["Phone is invalid"], ["messenger landing page"], ["Phone Metadata", "Caveats"], expected_outputs=["phone_posture"], risk_noise_notes=["No account-presence claims from generic deeplinks."]),
    PlaybookDefinition("maps_profile_review", "Maps Profile Review", "Parse analyst-supplied public Google Maps profile evidence and reviews.", ["google_maps_profile", "url"], [PlaybookStep("reviews", "Public reviews", "Extract visible public profile/review evidence.", "maps_profile_to_reviews")], ["maps_profile_to_reviews"], ["maps_place_to_place_details"], ["Input is not a public Maps URL"], ["screenshot-only evidence"], ["Reviews", "Place Metadata", "Confidence Caveats"], expected_outputs=["google_maps_review", "google_maps_place"]),
    PlaybookDefinition("evidence_validation", "Evidence Validation", "Map evidence to findings, score quality, and identify unsupported claims.", ["*"], [PlaybookStep("evidence_map", "Evidence map", "Build evidence-to-node and evidence-to-edge map."), PlaybookStep("quality", "Evidence quality", "Score source, freshness, directness, and report safety.")], [], [], ["No evidence records"], ["unsupported finding"], ["Evidence Map", "Unsupported Findings", "Quality Scores"], expected_outputs=["evidence_quality", "unsupported_findings"]),
    PlaybookDefinition("import_ioc_triage", "Import IOC Triage", "Preview analyst-provided IOC exports before graph insertion.", ["file"], [PlaybookStep("preview", "Preview import", "Parse CSV/JSON and map fields."), PlaybookStep("attach", "Attach evidence", "Store raw import as evidence before any graph write.", None, True)], [], ["spiderfoot_csv_import", "maltego_csv_import"], ["No source/legal note"], ["bulk unverified import"], ["Import Preview", "Evidence Attachment", "Mapping"], expected_outputs=["import_evidence", "mapping_preview"]),
    PlaybookDefinition("person_investigation", "Person Investigation", "Local-first person workflow: alias generation, browser-assisted public search, candidate review, and evidence-backed promotion.", ["person", "full_name", "alias"], [PlaybookStep("aliases", "Alias variants", "Generate local alias and username candidates.", "person_to_alias_variants"), PlaybookStep("search", "Browser-assisted public search", "Create safe search tasks and import evidence manually.", "person_to_search_queries", True), PlaybookStep("confirm", "Analyst confirmation", "Promote only evidence-supported candidates.", None, True)], ["person_to_alias_variants"], ["person_to_search_queries", "username_to_profile_candidates"], ["Only name variants exist", "No imported public evidence"], ["same username only", "login wall only"], ["Identity Summary", "Candidate Profiles", "Evidence", "Caveats"], expected_outputs=["alias_candidates", "profile_candidates", "collection_gaps"], risk_noise_notes=["Never attribute a real person from name or username similarity alone."]),
    PlaybookDefinition("organization_investigation", "Organization Investigation", "Normalize organization names, generate domain candidates, browser-assisted registry/document tasks, and evidence-backed ownership checks.", ["organization", "company", "brand"], [PlaybookStep("domains", "Domain candidates", "Generate candidate domains from brand/org names.", "org_to_domain_candidates"), PlaybookStep("search", "Public registry/document tasks", "Generate browser-assisted search tasks.", "org_to_search_queries", True)], ["org_to_domain_candidates"], ["org_to_search_queries", "domain_to_dns", "domain_to_rdap"], ["Official website evidence missing"], ["brand-name collision", "parked domain"], ["Organization Profile", "Domain Candidates", "Registry Evidence"], expected_outputs=["domain_candidates", "public_registry_tasks"]),
    PlaybookDefinition("reverse_image_investigation", "Reverse Image Investigation", "Hash analyst-provided image evidence, prepare reverse-search tasks, and cluster local similarity candidates.", ["image_asset", "screenshot", "avatar"], [PlaybookStep("hash", "Local image hashes", "Hash and fingerprint image evidence when binary pipeline is available.", "image_to_hashes", True), PlaybookStep("search", "Reverse search tasks", "Prepare browser-assisted reverse image tasks.", "image_to_reverse_search_queries", True)], [], ["image_to_hashes"], ["Image evidence missing"], ["visual lookalike without source"], ["Image Hashes", "Reverse Search Imports", "Similarity Candidates"], expected_outputs=["image_hash", "visual_match_candidate"], risk_noise_notes=["Visual matches remain candidates until source evidence is imported."]),
    PlaybookDefinition("location_maps_investigation", "Location/Maps Investigation", "Normalize location inputs, extract map/search tasks, and import public maps evidence.", ["location", "address", "coordinates", "google_maps_profile"], [PlaybookStep("search", "Location search tasks", "Generate map/public search tasks.", "location_to_search_queries", True), PlaybookStep("reviews", "Maps profile review", "Parse analyst-supplied public Maps profile/review evidence.", "maps_profile_to_reviews", True)], [], ["location_to_search_queries", "maps_profile_to_reviews"], ["No public source URL"], ["screenshot-only evidence"], ["Location Evidence", "Maps Reviews", "Caveats"], expected_outputs=["place_candidates", "maps_evidence"]),
    PlaybookDefinition("document_intelligence", "Document Intelligence", "Treat uploaded documents as evidence, extract hashes/entities/timeline, and generate graph pivots after analyst review.", ["document", "pdf", "office_document"], [PlaybookStep("hash", "Document hashes", "Hash uploaded document evidence.", "document_to_hashes", True), PlaybookStep("entities", "Entity extraction", "Extract links/emails/phones/domains where local parser is available.", "document_to_entities", True)], [], ["document_to_hashes"], ["No uploaded document evidence"], ["author metadata as unverified claim"], ["Document Metadata", "Embedded Entities", "Timeline"], expected_outputs=["file_hash", "embedded_entities", "timeline_events"]),
    PlaybookDefinition("vehicle_asset_investigation", "Vehicle/Asset Investigation", "Browser-assisted public mention workflow for vehicles, plates, VINs, vessels, aircraft, and asset tags.", ["vehicle", "license_plate_public", "vin_public", "vessel", "aircraft", "asset_tag"], [PlaybookStep("search", "Public mention tasks", "Generate browser-assisted public search tasks.", "vehicle_to_search_queries", True)], [], [], ["No public registration/source evidence"], ["restricted database expectation"], ["Public Mentions", "Candidate Records", "Evidence Caveats"], expected_outputs=["public_registration_candidate", "collection_gaps"], risk_noise_notes=["No restricted/private lookup dependency."]),
    PlaybookDefinition("threat_ioc_triage", "Threat IOC Triage", "Classify IOCs locally, run free passive pivots, and import external tool reports as evidence.", ["ioc", "domain", "ip", "url", "hash", "malware_hash"], [PlaybookStep("classify", "IOC type", "Classify IOC shape locally.", "ioc_to_type"), PlaybookStep("passive", "Passive enrichment", "Run DNS/RDAP/web metadata where applicable.", None, True), PlaybookStep("import", "Import reports", "Attach URLScan/VT/Shodan/Censys exports as evidence.", None, True)], ["ioc_to_type"], ["domain_to_dns", "ip_to_rdap_asn", "url_to_metadata"], ["No source evidence"], ["aggregator reputation without citation"], ["IOC Summary", "Passive Evidence", "Imported Reports"], expected_outputs=["ioc_type", "evidence_refs", "ioc_table"]),
    PlaybookDefinition("import_normalize_external_tool_output", "Import & Normalize External Tool Output", "Preview, map, store, and classify external free-tool outputs before graph promotion.", ["file"], [PlaybookStep("preview", "Preview file", "Detect format and map fields."), PlaybookStep("store", "Store as evidence", "Attach raw import as evidence first.", None, True), PlaybookStep("promote", "Promote candidates", "Analyst confirms graph candidates.", None, True)], [], ["spiderfoot_csv_import", "maltego_csv_import"], ["No source/legal note"], ["bulk import as verified graph"], ["Import Summary", "Candidate Leads", "Evidence Hashes"], expected_outputs=["import_evidence", "candidate_leads"]),
    PlaybookDefinition("report_preparation", "Report Preparation", "Validate evidence, review noise, resolve hypotheses, and prepare report-safe findings.", ["*"], [PlaybookStep("validation", "Validate findings", "Run validation and evidence map checks."), PlaybookStep("noise", "Review noise", "Inspect suppressed artifacts."), PlaybookStep("readiness", "Report readiness", "Calculate export blockers and warnings.")], [], [], ["Unresolved contradictions", "No evidence vault records"], ["unsupported finding"], ["Executive Summary", "Evidence Table", "Caveats", "Recommended Next Steps"]),
]


def list_playbooks() -> list[dict]:
    return [item.to_dict() for item in PLAYBOOKS]


def get_playbook(playbook_id: str) -> PlaybookDefinition | None:
    return next((item for item in PLAYBOOKS if item.id == playbook_id), None)
