from __future__ import annotations

from backend.playbooks.types import PlaybookDefinition, PlaybookStep


PLAYBOOKS = [
    PlaybookDefinition("email_investigation", "Email Investigation", "Validate mailbox syntax, workspace/domain posture, username candidates, and report-safe evidence.", ["email"], [PlaybookStep("email_workspace", "Workspace posture", "Resolve MX/TXT/provider posture.", "email_to_workspace"), PlaybookStep("email_gravatar", "Gravatar evidence", "Check public Gravatar avatar/profile evidence.", "email_to_gravatar"), PlaybookStep("email_username_candidates", "Username candidates", "Derive low-confidence username candidates from the email local-part.", "email_to_username_candidates"), PlaybookStep("email_profile_pivot", "Promote then profile pivot", "Promote a candidate username, then run Username -> Profiles with analyst confirmation.", None, True)], ["email_to_workspace", "email_to_gravatar", "email_to_username_candidates"], ["username_to_profiles", "email_to_breach_connectors"], ["No source URL or evidence hash", "Only candidates remain"], ["generic login pages", "candidate URL only"], ["Executive Summary", "Mailbox Posture", "Evidence", "Confidence", "Next Steps"]),
    PlaybookDefinition("username_investigation", "Username Investigation", "Resolve public profiles, links, avatar reuse, and weak/candidate separation.", ["username"], [PlaybookStep("username_profiles", "Public profile sweep", "Resolve target-specific public profile pages.", "username_to_profiles"), PlaybookStep("profile_links", "Profile link expansion", "Extract public profile links and self-declared websites.", "profile_to_links", True)], ["username_to_profiles"], ["profile_to_links", "profile_to_avatar"], ["No verified profile evidence"], ["soft 404", "auth wall", "generic login"], ["Profile Coverage", "Correlation", "Candidate Leads"]),
    PlaybookDefinition("domain_impersonation", "Domain Impersonation", "Compare domain infrastructure, RDAP, CT, favicon, and web fingerprint evidence.", ["domain", "url"], [PlaybookStep("domain_dns", "DNS posture", "Collect A/AAAA/MX/NS/TXT/CAA records.", "domain_to_dns"), PlaybookStep("domain_rdap", "RDAP", "Collect public registration/allocation metadata.", "domain_to_rdap"), PlaybookStep("domain_ct", "Certificate Transparency", "Collect public certificate names.", "domain_to_ct_subdomains"), PlaybookStep("favicon", "Favicon hash", "Compare reusable web asset fingerprints.", "domain_to_favicon_hash")], ["domain_to_dns", "domain_to_rdap"], ["domain_to_ct_subdomains", "domain_to_web_fingerprint", "domain_to_favicon_hash"], ["Official comparison domain missing"], ["CDN-only IP", "registrar privacy-only"], ["Risk Score", "Infrastructure Map", "IOC Table", "Takedown Notes"]),
    PlaybookDefinition("phone_investigation", "Phone Investigation", "Validate numbering plan and public-source/manual evidence without contact-sync abuse.", ["phone"], [PlaybookStep("numbering", "Numbering plan", "Validate E.164, carrier/region metadata.", "phone_to_numbering_plan"), PlaybookStep("deeplinks", "Public deeplink metadata", "Collect only public metadata; never claim registration from landing pages.", "phone_to_public_deeplinks", True)], ["phone_to_numbering_plan"], ["phone_to_public_deeplinks"], ["Phone is not valid E.164"], ["messenger landing page"], ["Phone Metadata", "Manual Evidence", "Caveats"]),
    PlaybookDefinition("crypto_wallet_investigation", "Crypto Wallet Investigation", "Collect public explorer balance/transaction pivots through configured connectors.", ["crypto_wallet"], [PlaybookStep("balance", "Wallet balance", "Fetch public explorer balance if connector is configured.", "check_wallet_balance"), PlaybookStep("trace", "Transaction trace", "Expand public transaction links with analyst confirmation.", "trace_transactions", True)], ["check_wallet_balance"], ["trace_transactions"], ["No public explorer connector configured"], ["dust spam transactions"], ["Wallet Summary", "Transactions", "Counterparties"]),
    PlaybookDefinition("website_clone_detection", "Website Clone Detection", "Compare web fingerprints, favicons, links, DNS, and CT evidence.", ["domain", "url"], [PlaybookStep("fingerprint", "Web fingerprint", "Collect public headers/title/meta and favicon.", "domain_to_web_fingerprint"), PlaybookStep("assets", "Asset reuse", "Hash visible web assets where public.", "domain_to_assets", True)], ["domain_to_web_fingerprint"], ["domain_to_assets", "domain_to_favicon_hash"], ["No official/source comparison evidence"], ["generic template pages"], ["Clone Indicators", "Shared Assets", "Evidence"]),
    PlaybookDefinition("threat_actor_infrastructure_mapping", "Threat Infrastructure Mapping", "Map public domain/IP/ASN/certificate relationships without private collection.", ["domain", "ip", "url"], [PlaybookStep("infra_dns", "DNS/IP map", "Collect DNS and reverse DNS.", "domain_to_dns"), PlaybookStep("rdap_asn", "RDAP/ASN", "Collect public allocation metadata.", "ip_to_rdap_asn"), PlaybookStep("ct", "CT expansion", "Expand certificate names cautiously.", "domain_to_ct_subdomains", True)], ["domain_to_dns", "ip_to_rdap_asn"], ["domain_to_ct_subdomains", "ip_to_reverse_dns"], ["Only CDN/shared hosting remains"], ["CDN-only", "shared hosting"], ["Infrastructure Map", "Confidence", "Noise Removed"]),
    PlaybookDefinition("report_preparation", "Report Preparation", "Validate evidence, review noise, resolve hypotheses, and prepare report-safe findings.", ["*"], [PlaybookStep("validation", "Validate findings", "Run validation and evidence map checks."), PlaybookStep("noise", "Review noise", "Inspect suppressed artifacts."), PlaybookStep("readiness", "Report readiness", "Calculate export blockers and warnings.")], [], [], ["Unresolved contradictions", "No evidence vault records"], ["unsupported finding"], ["Executive Summary", "Evidence Table", "Caveats", "Recommended Next Steps"]),
]


def list_playbooks() -> list[dict]:
    return [item.to_dict() for item in PLAYBOOKS]


def get_playbook(playbook_id: str) -> PlaybookDefinition | None:
    return next((item for item in PLAYBOOKS if item.id == playbook_id), None)
